### ISSUE TITLE
Icon for .mp4 video files :)

### ISSUE THREAD

**Issue by Hassan2402** [DS-Homebrew/TWiLightMenu#1312] opened 2021-01-15 04:07 UTC
**Is your feature request related to a problem? Please describe.**
All files in Twilight Menu ++ have an icon for easy identification. This is not the case with MP4 videos that retain a generic icon.
![image](https://user-images.githubusercontent.com/77475401/104680139-f7c37b80-56cd-11eb-9cf5-68765d4dd678.png)

**Describe the solution you'd like**
Is it possible to add an icon for .MP4 video files? It could be similar to this:
![image](https://user-images.githubusercontent.com/77475401/104680042-bb901b00-56cd-11eb-9d25-e2aff053aa5b.png)

Thanks!

**Comment by RocketRobz** [comment] 2021-01-15 04:20
Duplicate of #1119

**Closed by RocketRobz** 2021-01-15 04:20 UTC
Labels: enhancement
