### ISSUE TITLE
Themes other than dsi theme not showing their sub themes

### ISSUE THREAD

**Issue by shinogirl** [DS-Homebrew/TWiLightMenu#910] opened 2020-02-15 19:52 UTC
**Your console configuration:** DSI And Unlaunch
**TWiLight Menu++ Version:** v12.0.0: TWLMenu++ XL/LL edition (Valentine's Day release)
**TWiLight Menu++ Theme:**NA

### Expected behaviour
Sub themes menu should show the sub themes in the proper folder

### Actual behaviour

Blank screen that can make noises like its scrolling through a list but is unable to select anything

### Steps to reproduce

1. Go to sub theme menu
2.see blanks screen
3. Try to scroll or stuff
4. Be sad cus miku theme won't appear

**Comment by NightYoshi370** [comment] 2020-03-25 20:23
I can't reproduce. I see the Hatsune Miku theme just fine. It's probably a bug on your end.
Closing...

**Closed by NightYoshi370** 2020-03-25 20:23 UTC
Labels: bug
