### ISSUE TITLE
Flashcard DsTwo+ Black Screen Red Squares

### ISSUE THREAD

**Issue by frostheart32** [DS-Homebrew/TWiLightMenu#1090] opened 2020-06-20 12:34 UTC
**Your console configuration:**  New 3DS with Luma3DS
**TWiLight Menu++ Version:**  15.2.0
**TWiLight Menu++ Theme:**  DSi

### Expected behaviour

 Launch DSTwo+ cart, to DSTwo firmware menu

### Actual behaviour

 Launch starts with a hang on a white screen for 2-5 seconds and then the bottom screen goes black with 4 red squares. The 4th Block turns yellow, then green, then red again. The 3rd Block turns red.

### Steps to reproduce

1. I have run this situation with increased CPU speed and Mrs, with VRAM boosted and not, with increased sound frequency on and off, with nds-bootstrape option set to yes and no, and with sgfc set to on and off. All yield the same result.
2. I have used the twlfix and did a system update with no difference. I have deleted and reinstalled twilight menu, using both the sd boot manual install and the flashcart boot manual install. I have then used twilight updater to try both the latest release and the nightly release. All yield the same result.
3. I originally installed twilight menu last year, and tested using my flashcart recently, using flashcart firmware, with increased CPU speed, boosted VRAM and increased sound frequency successfully. I would boot from the classic ds menu. It would hang on a white screen for 2-5 secs and load to the flashcart firmware ~2 out of 5 loads. To try see if an update would increase the successful load attempts, I updated to the newest version, leading to the above issue.

Thanks,
Frosty

**Comment by RocketRobz** [comment] 2020-06-20 15:09
Duplicate of #1040

**Closed by RocketRobz** 2020-06-20 15:09 UTC
Labels: bug
