### ISSUE TITLE
Small graphic bug

### ISSUE THREAD

**Issue by Animacreep** [DS-Homebrew/TWiLightMenu#410] opened 2019-02-15 16:19 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only
- [X]  Unlaunch+HiyaCFW (Unlaunch 1.8 and the latest HiyaCFW)

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release 7.4.0
- [ ]  Nightly

### Expected behaviour

When I go into my SNES games folder and try to move the emulator (the NDS of the emulator) there should be nothing to the right when there's an icon at that side.

### Actual behaviour

There's a weird icon to the right of the NDS. I think it's because of the video on the upper screen. There's also a small flicker in a zone of the bottom screen.

### Steps to reproduce

1. Create a folder (I called mine "SNES")
2. Have a game (Earthbound in this case), the SNES emulator (on NDS format) and the ramdisk folder inside this SNES folder.
3. Try to move the emulator. There's a glitched icon in one side.

I attached a gif file with a video.
![gif](https://user-images.githubusercontent.com/34885906/52869138-46181a80-3145-11e9-8980-6f207f049de5.gif)

**Comment by meltstrap** [comment] 2019-02-15 18:04
I'm having the same issue on the 3DS theme. Also, scrolling on my DSi is extremely unresponsive.

**Comment by RocketRobz** [comment] 2019-02-15 19:13
Scrolling is sometimes unresponsive for me. It's because of the colon blinking in the time.

**Comment by RS55** [comment] 2019-02-22 04:08
It also happened to me, only that it was with the last scroll icon, I deleted it and it continued, it started and it was hung, I had to delete the file with the order of the games to solve it

**Comment by NightYoshi370** [comment] 2020-02-18 21:35
This issue has been opened for a year. Can anyone reproduce it though?

**Comment by NightYoshi370** [comment] 2020-03-25 20:25
Ok, I cannot reproduce this. Plus, there are now differences with how the moving code works (for example, there is now little squares in the middle indicating where you could place the icon)
Closing...

**Closed by NightYoshi370** 2020-03-25 20:25 UTC
