### ISSUE TITLE
there is no AK theme available in setting menu

### ISSUE THREAD

**Issue by asd2727023** [DS-Homebrew/TWiLightMenu#1279] opened 2020-12-29 16:32 UTC
**Console Configuration:**  The system
**TWiLight Menu++ Version:** 
v18.0.0
**TWiLight Menu++ Theme:** 
I can't set AK theme 
### Expected behaviour
I want to use the AK theme. I can't find the AK theme in setting menu. There are original R4, 3ds, dsi, sega, gba but no AK. 

### Steps to reproduce

1. Enter select to setting menu 
2. Turn to theme
3.  Turn left or right and you won't find the AK theme …

**Comment by NightYoshi370** [comment] 2020-12-29 18:21
Dupe of #1104
The wood UI will not return until it is fixed.

**Closed by NightYoshi370** 2020-12-29 18:21 UTC
Labels: bug
