### ISSUE TITLE
Twm v24.6 don't let DSI ll go on sleep mode, is 24.7 fixing this?

### ISSUE THREAD

**Issue by Akirah10** [DS-Homebrew/TWiLightMenu#1928] opened 2022-05-06 20:51 UTC
**Console Configuration:**  DSI LL, hiyacfw + unlaunch
**TWiLight Menu++ Version:**  twilight menu v 24.6 earthday
**TWiLight Menu++ Theme:** 

### Steps to reproduce

1.
2.
3.

**Comment by lifehackerhansol** [comment] 2022-05-06 21:03
Duplicate of #1409.

**Closed by lifehackerhansol** 2022-05-06 21:03 UTC
Labels: bug

**Comment by Akirah10** [comment] 2022-05-06 23:01
Sorry, but it's not a duplicate. I don't have any glitch on my top screen. It's a simple no sleep mode, except when it's on twilight menu. While in twilight menu, it works properly, u close the lid and go to sleep mode. When u get out of it, it won't go to sleep mode, resulting in draining the battery. So please, maybe ask me before closing an issue that still not resolved?. Thanks.

**Comment by RocketRobz** [comment] 2022-05-06 23:03
Sleep mode doesn't work because of the issue @lifehackerhansol mentioned earlier.
It does not work while in the DSi, 3DS, Saturn, and HBL themes.

**Comment by lifehackerhansol** [comment] 2022-05-06 23:06
Also, please actually fill out the forms next time instead of leaving everything blank. They are there for a reason.

**Comment by Akirah10** [comment] 2022-05-06 23:11
Hey, I am new here. A bit of consideration could be nice. I didn't know how to fill the form. Now is filled, I opened again. I didn't see any message or answer from the other developer, so my apologies, but as u can see he only wrote that was a duplicate. I apologize about the form, but I'm new here, so bare with me. Instead of all this drama, could be nice to suggest any solution, maybe to go back to any version lower than 24.6?

**Comment by lifehackerhansol** [comment] 2022-05-06 23:14
The best course of action is to avoid the DSi/3DS/Saturn/HBL themes. The other two themes do not have this bug and thus sleep mode continues to be enabled there.

That or turn off the DSi. I suppose both are solutions.

**Comment by Akirah10** [comment] 2022-05-06 23:15
U supposed well. Thanks.
