### ISSUE TITLE
Error in Mario vs Donkey Kong MiniLand Mayhem in the Twilight menu

### ISSUE THREAD

**Issue by Master9012** [DS-Homebrew/TWiLightMenu#1254] opened 2020-12-07 00:17 UTC
I downloaded the mario vs donkey kong miniland mayhem in the twilight menu, when I start it everything goes well, until I start a game, the Mini Marios are invisible

**Comment by RocketRobz** [comment] 2020-12-07 00:19
Duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/467

**Closed by RocketRobz** 2020-12-07 00:19 UTC
Labels: bug
