### ISSUE TITLE
3DS theme: Black lines on top icons on bottom screen

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/TWiLightMenu#1866] opened 2022-03-26 05:27 UTC
**Console Configuration:** OLD 3DS XL with Luma 10.3 and GM9 2.1.1 and DSi XL with Unlaunch
**TWiLight Menu++ Version:** [v24.2.1: MAR10 Day (2022) (hotfix)
**TWiLight Menu++ Theme:** Nintendo 3DS (dark and light)

### Expected behaviour
1. Rotating cubes should disappear when the box art of any ROM appears.
2. Those black lines on the Cartridge and Manual icons shouldn't be there. 

Hi, I'm back after a good time of inactivity.
I come to highlight two errors that occur on my two consoles (DSi and 3DS)
The first one, and this one I already reported in #1367, only the current behavior is a bit different, the cubes continue to appear behind the boxarts but, this time, completely randomly when scrolling between games with the d-pad. This happens quite often. I leave a photo to explain myself better: 
![image](https://user-images.githubusercontent.com/70182567/160226062-2e433e45-0b18-4a68-82ef-b24f4c11e87a.png)

The second bug is that little black lines appear on the cartridge and manual icons, when scrolling between games. I tried to record a video to show it, but it's easier to see with the naked eye (sorry about the video quality): 
https://user-images.githubusercontent.com/70182567/160226084-3dcb1544-76c0-42c8-bf39-857f47f36225.mp4

Big hug guys!

**Comment by RocketRobz** [comment] 2022-03-26 05:30
1. I don't see how that bug is still occurring. Are you using the latest nightly? If so, I can't reproduce it on my end, even when scrolling between games.
2. That bug is fixed by turning off photo/box art color de-banding.

**Comment by SofyUchiha** [comment] 2022-03-26 05:40
1. Yes. Is the 24.2.1 Version... 
![image](https://user-images.githubusercontent.com/70182567/160226464-38bfa5f4-1427-46c4-80fb-29b0f2bc5d49.png)

2. The off photo/box art color de-banding is off 😢 
![image](https://user-images.githubusercontent.com/70182567/160226472-35644a9e-580e-4e42-929d-9ecf3a59a991.png)

**Comment by RocketRobz** [comment] 2022-03-26 05:42
1. No, that's the current release version. The nightly version is different, and can be downloaded using Universal-Updater.
2. That's weird. Maybe check if the nightly fixes it then?

**Comment by SofyUchiha** [comment] 2022-03-26 05:49
Same bug 😞 look:

https://user-images.githubusercontent.com/70182567/160226710-15b3da32-e387-4ed5-acb3-6d7411ba55e4.mp4

**Comment by RocketRobz** [comment] 2022-03-26 05:52
v24.2.1 is not a nightly version. Please open Universal-Updater, select TWiLight Menu++, and select the nightly option.

**Comment by SofyUchiha** [comment] 2022-03-26 06:09
![image](https://user-images.githubusercontent.com/70182567/160227181-c38ff76e-cae2-4700-9927-a342496dd583.png)
This... Right?

**Comment by RocketRobz** [comment] 2022-03-26 06:09
Yes, that one.

**Comment by SofyUchiha** [comment] 2022-03-26 06:21
Verdict:
- The first bug has been fixed!
- Second bug: the black lines on the manual and cartridge icons are even more visible than before (The off photo/box art color de-banding is off )

**Comment by spellboundtriangle** [comment] 2022-12-18 08:40
According to @Gericom, the second bug may be due to loading the textures outside of vblank

**Comment by RocketRobz** [comment] 2023-08-04 05:47
Seems to be fixed by fb3b12a57

**Closed by RocketRobz** 2023-08-04 05:47 UTC
Labels: bug, DSi/3DS/Saturn/HBL Theme
