### ISSUE TITLE
Add Back akmenu theme

### ISSUE THREAD

**Issue by DraconicNEO** [DS-Homebrew/TWiLightMenu#1599] opened 2021-08-28 01:37 UTC
**Is your feature request related to a problem? Please describe.**
I think it would be nice if the akmenu theme was added back to Twilight Menu, since it was removed for an unknown reason.

**Describe the solution you'd like**
Add akmenu theme back to Twilight Menu.

**Describe alternatives you've considered**
[Doesn't apply here]

**Additional context**
If akmenu was removed for a good reason please explain why, it seems like it was just silently removed without reason or mention in any changelogs.

**Comment by RocketRobz** [comment] 2021-08-28 01:41
It has been mentioned in the GBATemp thread and Discord server, that it got removed because it would corrupt the SD card.
Re-adding libslim could theoretically fix that, but is unstable at the moment.

Closing as duplicate of #1104

**Comment by RocketRobz** [comment] 2021-08-28 01:41
Duplicate of #1104

**Comment by Epicpkmn11** [comment] 2021-08-28 01:41
Also, see #1109 for progress on fixing it

**Closed by RocketRobz** 2021-08-28 01:41 UTC
Labels: enhancement
