### ISSUE TITLE
Request to repair WoodUI

### ISSUE THREAD

**Issue by Aeuko** [DS-Homebrew/TWiLightMenu#1047] opened 2020-05-28 01:37 UTC
-TWiLight Menu++ Version v15.1.1
-WoodUI

 use it for the first time, reset the NDSI theme to set WoodUI after booting, restart into WoodUI, all GB games fail to run, and restarted games are blank.

**Comment by chyyran** [comment] 2020-07-05 21:57
dupe of https://github.com/DS-Homebrew/TWiLightMenu/issues/1078

**Closed by chyyran** 2020-07-05 21:57 UTC
Labels: bug
