### ISSUE TITLE
Failed to apply 4 firm patches starting Twilight Menu

### ISSUE THREAD

**Issue by donnumski** [DS-Homebrew/TWiLightMenu#1946] opened 2022-06-11 00:32 UTC
**Console Configuration:New 3DS with Luma3DS v11,0
**TWiLight Menu++ Version: v24.9.1
**TWiLight Menu++ Theme: 3DS

### Expected behaviour
Starting the Twilight by the Twilight app on the 3DS menu

 Booting into Twilight Menu

### Actual behaviour

When i try to open TWiLightMenu++ after install i see an error;

An error has occurred:

Failed to apply 4 FIRM patch(es)

Press any button to shutdown

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment] 2022-06-11 01:14
Duplicate of #974

**Comment by RocketRobz** [comment] 2022-06-11 01:15
Also, this is not a TWiLight Menu++ issue. If you need help with fixing this, then please join our Discord server.

**Closed by RocketRobz** 2022-06-11 01:14 UTC
Labels: bug

**Comment by donnumski** [comment] 2022-06-11 01:41
Hi. It happened when I first installed a nds forwarder and then the Twilight. I found out that the same error occured when I tried to play a physical DS game.But I found the solution now. I had to run the TWL fix program and update my system. Now all is very good. It seems that nds forwarder and Twilight crashes when both are installed. Why this happens is beyond me abbility.

Brgds Tom

Sendt fra E-post for Windows

Fra: RocketRobz
Sendt: lørdag 11. juni 2022 kl. 03:15
Til: DS-Homebrew/TWiLightMenu
Kopi: donnumski; Author
Emne: Re: [DS-Homebrew/TWiLightMenu] Failed to apply 4 firm patchesstarting Twilight Menu (Issue #1946)

Also, this is not a TWiLight Menu++ issue. If you need help with fixing this, then please join our Discord server.
