### ISSUE TITLE
Softlock after changing "cached" to "none"

### ISSUE THREAD

**Issue by CapNinja** [DS-Homebrew/TWiLightMenu#1285] opened 2021-01-01 06:39 UTC
Using the Christmas 2020 update.

If you change like the title says, buttons and touchscreen will stop working, except "home button". Using the tip on pinned comment "turn it on with select pressed" helped to go back and now it's ok. I'm using dsi theme and new 3ds XL.
Thanks a lot

**Comment by urmum-69** [comment] 2021-01-01 06:39
if the issue is resolved, you should close it?

**Closed** 2021-01-01 06:43 UTC
