### ISSUE TITLE
Private Server like in UsbloaderGX

### ISSUE THREAD

**Issue by DraconicNEO** [DS-Homebrew/TWiLightMenu#1245] opened 2020-11-27 07:39 UTC
**Is your feature request related to a problem? Please describe.**

I feel like it would be good to have a private server option in twilight menu similar to the private server option in UsbloaderGX because you wouldn't need to patch games or use a custom DNS to go online.

**Describe the solution you'd like**

This feature would add a patcher that patches the URLs in memory without modifying the games similar to how UsbloaderGX works.
There would be a menu (either game specific or global) that selects between a list of Private servers and user defined entries. It's important to allow user defined entries in case server URLs ever change or there are any new servers available.

**Describe alternatives you've considered**

An Emulator with this ability.

**Additional context**

N/A

**Comment by RocketRobz** [comment] 2020-11-27 07:40
Duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/1044

**Closed by RocketRobz** 2020-11-27 07:40 UTC
Labels: enhancement
