### ISSUE TITLE
Simplify Folder Distribution, please

### ISSUE THREAD

**Issue by LabregoPT** [DS-Homebrew/TWiLightMenu#971] opened 2020-04-01 16:44 UTC
**Is your feature request related to a problem? Please describe.**
I love Twilight Menu, but I'm really dissappointed on how badly organized are its files. Several features require a cluster of files which are really not necessary for all users, such as Widescreen or Themes. This really increases the time of extraction, update, and instalation in SD.

**Describe the solution you'd like**
Include files for optional features as a separate download, so as users who don't really use them (like me) would not be forced to include them as well.
You could have a different download including all of the files, so users who are comfortable with files as they already are would have them already.

**Describe alternatives you've considered**
Simply deleting the files for widescreen patches and themes I'm not using before placing the files on my SD Card

**Comment by NightYoshi370** [comment] 2020-04-01 16:46
Dupe of #918 
Closing

**Closed by NightYoshi370** 2020-04-01 16:46 UTC
Labels: enhancement

**Comment by LabregoPT** [comment] 2020-04-01 16:50
Not a dupe of #918, as #918 asks to adjust tutorials and place folders for different instalations in sepparate files, and I'm asking you to make optional features like, you know, _optional_

**Comment by NightYoshi370** [comment] 2020-04-01 16:50
Look at the comment of #918 made by Lark

**Comment by LabregoPT** [comment] 2020-04-01 16:54
Ok, if that's the case, I will add this as a comment there so it goes noticed in an open issue
