### ISSUE TITLE
Some cheat listings cause TWLMenu++ to crash and restart

### ISSUE THREAD

**Issue by Dhalian** [DS-Homebrew/TWiLightMenu#1592] opened 2021-08-20 14:56 UTC
**Console Configuration:** New Nintendo 2DS XL - Luma 10.2.1
**TWiLight Menu++ Version:** 21.4.0
**nds-bootstrap Version :** 0.46.1(Release)
**TWiLight Menu++ Theme:** Regular White DSi 

### Expected behaviour

 Open the cheat menu / Get back to the TWiLightMenu

### Actual behaviour

 When i select open the Cheats menu for some games (tested with Super Mario 64 DS and TRACKMANIA DS), it reboot the TWiLightMenu or try to reboot the TWiLightMenu (sometimes get stuck at a white screen) / and when i want to go back to the menu (from the in game menu) it gives me a white screen randomly(tested with GTA CW)

### Steps to reproduce

1.Open the cheat menu of games like Super Mario 64 DS or TRACKMANIA DS
2.Open the in game menu in GTA CW and click on "Return to menu"

**Comment by christopher3242** [comment] 2021-08-20 18:58
Oh

**Comment by Squall-Leonhart** [comment] 2021-08-23 04:43
close then open the lid

**Comment by Dhalian** [comment] 2021-08-24 09:36
> close then open the lid

if it was that easy I wouldn't have created an Issue, obviously doing this doesn't solve my problem!

**Comment by RocketRobz** [comment] 2021-08-24 09:38
Try a different `usrcheat.dat` file then, or turn off box art caching.

**Comment by Dhalian** [comment] 2021-08-24 09:39
> Try a different `usrcheat.dat` file then, or turn off box art caching.

I'll try with a different usrcheat, i don't use the Boxarts personally

**Comment by Epicpkmn11** [comment] 2022-03-28 23:54
Is this still an issue? iirc I couldn't reproduce it but if it's still an issue I'll look into it.

**Comment by spellboundtriangle** [comment] 2022-09-14 10:39
I'm not encountering it either, with American SM64DS rev 1 at least

**Comment by lifehackerhansol** [comment] 2022-09-22 18:19
Closing as we have not heard any reports of this since.

Should anyone continue to encounter this issue, please feel free to reopen or leave a comment.

**Closed** 2022-09-22 18:19 UTC
Labels: bug

**Comment by scudo005** [comment] 2026-09-01 08:16
I encountered this issue, my `usrcheat.dat` must be broken somehow because by trying to load the cheat menu for some games TWLMenu++ crashes and restarts.

This prevents me from loading some games.

Right now I have no means to read the SD card, I will send you the logs (and my `usrcheat.dat` if you need it) when I have the chance.

**Comment by RocketRobz** [comment] 2026-09-01 08:21
The issue is caused by the list allocating too much RAM space. Try changing the UI to R4, GBC, or Wood, and see if it fixes your issue.

**Comment by scudo005** [comment] 2026-09-01 08:31
Changing the UI made no difference, and the ROMs boot just fine in melonDS. Though I got a new error this time:
![20260901_102935.jpg](https://github.com/user-attachments/assets/eb4df025-add2-4146-ac08-b176c95e5551)

**Comment by RocketRobz** [comment] 2026-09-01 08:35
> Changing the UI made no difference, and the ROMs boot just fine in melonDS. Though I got a new error this time

When does that error appear? Because it looks like the per-game settings menu (where you'd open the cheat menu from there) isn't open at that point.

**Comment by scudo005** [comment] 2026-09-01 22:46
The error appears when starting the game.
