### ISSUE TITLE
TWiLight Menu goes widescreen after launching game in widescreen

### ISSUE THREAD

**Issue by firelad97** [DS-Homebrew/TWiLightMenu#950] opened 2020-03-23 18:06 UTC
**Your console configuration:**   New 2DS with Luma3DS
**TWiLight Menu++ Version:**  12.2.1
**TWiLight Menu++ Theme:**  DSi

### Expected behaviour

 TWiLight Menu++ should retain in 4:3 ratio as was specified in the TWL settings. Each game I use for 16:10 widescreen is specified via a per-game config. Exiting game back to TWL or restarting TWL via 3DS Home and starting TWL again should still retained in 4:3 not 16:10.

### Actual behaviour

 Going in the widescreen after launching game in TWL seem to cause other games go in widescreen. Reinstalled TWL, launched "Last Run ROM" title via FBI, still in widescreen. Deleted the .cxi file in Luma/sysmodules, and noticed that Widescreen.cxi disappeared. Made a new one, and then moved .cxi file and renamed it.

Continues to have the same issue after everything I've done. I have to make the back up of Widescreen.cxi and do it everytime I launch the game in widescreen. (Widescreen cheats also seem to not apply here, such as Final Fantasy The 4 Heroes of Light, notably when using alternative one.)

EDIT: Forgot to add that I already had tried deleting TWL titles in FBI twice. My apologies.

### Steps to reproduce

1. Launch the game in widescreen (ie, Super Mario 64 DS)
2. Exit the game to TWL or return to 3DS Home and restart TWL
3. TWL and rest of games/homebrews are now in widescreen

**Comment by RocketRobz** [comment] 2020-03-23 18:09
Try deleting the TWiLight Menu++ titles in FBI, then reinstall the CIAs.

**Comment by firelad97** [comment] 2020-03-23 18:23
Sorry, should be more a bit clear in my first post. I've already tried deleting TWL titles in FBI twice.

**Comment by firelad97** [comment] 2020-03-24 06:11
Thinking on it, it might be that widescreen patch (Widescreen.cxi) isn't persistent. Intended? The problem with this is, after launching a specific game in widescreen, the patch disappears and create a new .cxi in Luma/sysmodules everytime it happens. Afterwards, that new .cxi file is permanent there, thus making all NDS applications stay in widescreen and the patch doesn't apply anymore unless deleted.

The only workaround to this, from what I see, is by deleting .cxi file in Luma/sysmodules everytime when exiting the game in widescreen and then re-add Widescreen.cxi I had backed up so the patch will still work afterwards until next time game in widescreen starts again.

**Comment by RocketRobz** [comment] 2020-03-24 06:19
None of this is intended.
After switching to widescreen, TWLMenu++ is supposed to rename `TwlBg.cxi` back to `Widescreen.cxi`, and move it back to `sd:/_nds/TWiLightMenu/TwlBg/`.

**Comment by firelad97** [comment] 2020-03-24 07:10
Gotcha. Looking forward to a fix, this is pretty annoying for me tbh

**Comment by Rainoutt** [comment] 2020-04-26 09:46
I can confirm this also happens to me. Also Widescreen.cxi gets deleted from it's folder TwlBg, is this intended?

**Comment by RocketRobz** [comment] 2020-04-26 17:59
@Rainoutt Read my above post.

**Comment by SleepyLark** [comment] 2020-04-27 18:02
So this issue only happens when the Aspect Ratio is set to "4:3" on the TWL settings but the game is overridden to use "16:10".  Doing the inverse ("16:10" in the TWL settings, "4:3" in the per-game settings) doesn't have this issue.  So I'm guessing whatever function is being used to move the file back from sysmodules isn't being used when the TWL settings is set to "4:3", so maybe add like a check to see if TwlBg.cxi is in the sysmodules folder regardless if the settings is set to "16:10" (the again there may be some people who want widescreen for every game so they have it there regardless), or have it move the file if it detects Widescreen has been activated in the per-game settings (or fix whatever is causing it to not do it if you already have this).  That's my perspective of the problem, if it helps at all

**Comment by firelad97** [comment] 2020-05-01 11:45
@SleepyLark Mine's different. Aspect Ratio being set to 4:3 just renders all games in 4:3, no 16:10. My issue was only present as what I had described, while in 16:10.

**Comment by danylopez123** [comment] 2020-05-17 17:41
I just got the same problem, ecept that was in my Old 3DS with Luma3DS

**Comment by danylopez123** [comment] 2020-05-18 14:23
Ok, so, not only the TwilightMenu++ who gets stuck in Widescreen, but when i went to play a DSiWare game, it still stayed in Widescreen, im guessing this will do the same for a normal NDS game.

**Comment by SleepyLark** [comment] 2020-05-19 00:28
> 
> 
> Ok, so, not only the TwilightMenu++ who gets stuck in Widescreen, but when i went to play a DSiWare game, it still stayed in Widescreen, im guessing this will do the same for a normal NDS game.

@danylopez123 That's because "TwlBg.cxi" is still in the `luma/payloads/` folder, meaning it's getting applied when ever you switch to TWL_firm (meaning it will do this for DSiWare and NDS cartridges).  Like I said earlier, TWiLight Menu is supposed to move it out of that folder once the game closes so it doesn't affect other titles but for some reason it's not doing it.  Just rename it back to "Widescreen.cxi" and move it back to wear it belongs in the "TWiLight Menu" folder and change the settings in TWiLight Menu so the Aspect Ratio is always "16:9" and change the per-game settings to "4:3" on what ever games you don't want to be widescreen (not all games even have support for widescreen so you may not even need to change it)

**Comment by RocketRobz** [comment] 2020-05-19 08:03
Make sure TWiLight Menu++ is up to date. If it already is, then install the latest CIAs manually, using FBI.
Recent versions now copy `Widescreen.cxi` instead of moving it.

**Comment by danylopez123** [comment] 2020-05-19 14:56
@SleepyLark Actually that file went to luma/sysmodules for me.
At least thanks for letting me know, i will stay in the normal screen until there is a fix for that + i were using the most recent version and still does the same thing.

**Comment by kescherCode** [comment] 2020-05-27 11:41
Everything will be widescreen until TwlBg.cxi under /luma/sysmodules is either deleted, or replaced with what was there before TWiLiight places it there. I am always manually reverting this change, since TWiLight Menu doesn't seem to do this by itself.

**Comment by CatsLover2006** [comment] 2020-07-26 15:58
Is this dead?

**Comment by ryotoko** [comment] 2020-08-06 03:18
I am still getting this on 16.00. I used L+R+Down+B to exit the game, so maybe that's why? Is there a proper way to exit the game so that files are properly restored?

**Comment by RocketRobz** [comment] 2020-08-06 03:25
That's not why this issue occurs. The TwlBg file is reverted before the game boots, so that TWiLight Menu++ doesn't boot in widescreen.
Also, the widescreen guide has been updated. Have you re-followed the guide when the update released?

**Comment by ryotoko** [comment] 2020-08-06 03:28
I did follow the recent guide, just set this up today.
I found a TwlBg.cxi and TwlBg_bak.cxi in the luma/sysmodules dir. Restoring it manually worked

**Comment by ccfman2004** [comment] 2020-08-19 21:28
I also have this same issue where TwiLightMenu is in Widescreen

**Comment by RocketRobz** [comment] 2020-09-05 06:55
Starting with 277230e4, widescreen will be handled differently.

**Closed by RocketRobz** 2020-09-05 06:55 UTC
Labels: bug

**Comment by jvook** [comment] 2021-12-04 01:42
I turned on widescreen as default in the settings menu and it won't go back to 4:3.  Also the option for widescreen mode in the settings menu seemed to disappear. Changing settings.ini to widescreen=0 didn't fix it.  There is nothing in my TwlBg folder.  So I will try to move the TwlBg to Widescreen.cxi.
...
OK that seems to have fixed it.  The option is also back (Am I crazy I looked for 5 minutes but it's possible I just missed it).

As a side note is there an ini file out there that has the Widescreen toggled on for all of the games that use Widescreen?

**Comment by RocketRobz** [comment] 2021-12-04 01:44
To toggle it on for all supported games, it needs to be toggled in TWLMenu++ Settings.

**Comment by jvook** [comment] 2021-12-04 02:15
That's actually what I was trying when I ran into the problem of being stuck in widescreen.  When I did that the first thing I tried was Advance Wars which I know is unsupported and it came up widescreen then I couldn't get out of widescreen.   I just tried it again though and it worked as you said so I guess my TwlBg.cxi glitched and that's why it seemed like every game was coming up widescreen.

**Comment by Slugthedino** [comment] 2024-09-20 22:46
I ran into this same glitch today by putting a bunch of cheats on and fixed it by deleting widescreen.pck somewhere in _nds (I just pressed Ctrl f in sd card then typed that and deleted it.) and the TwlBg.cxi in luma sys modules. For some reason if you reninstall the patch again it doesn't work ever again but brings your DS games on home menu and twilight menu back to normal size.
