### ISSUE TITLE
Select menu: Open Manual icon is wrong

### ISSUE THREAD

**Issue by gingerbeardman** [DS-Homebrew/TWiLightMenu#863] opened 2020-01-11 13:23 UTC
**Your console configuration:** DSi XL with Unlaunch 2.0, HiyaCFW 1.3.2
**TWiLight Menu++ Version:** v11.2.0: TWL Christmas release
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

Open Manual should have small icon of its own.

### Actual behaviour

Open Manual icon is one from a game I have.

### Steps to reproduce

1. Use latest TWLM

### Photos

![SELECT menu](https://i.imgur.com/O1LP4mD.jpg)

![Game list](https://i.imgur.com/8M3RDof.jpg)

**Comment by RocketRobz** [comment] 2020-01-11 19:52
That didn't happen for me, last time I tried to fix it.

**Comment by gingerbeardman** [comment] 2020-01-13 11:47
Would it help if I zipped up my config?

**Comment by NightYoshi370** [comment] 2020-02-18 21:43
Well, this issue isn't necessarily *fixed* but it is now invalid since we don't use the SELECT Menu anymore.
Closing

**Closed by NightYoshi370** 2020-02-18 21:43 UTC
Labels: bug, help wanted

**Comment by gingerbeardman** [comment] 2020-02-18 23:30
Thanks for the heads-up!

**Comment by gingerbeardman** [comment] 2020-02-21 15:15
https://github.com/DS-Homebrew/TWiLightMenu/tree/v12.1.0

- the SELECT menu returns?

@NightYoshi370

**Comment by NightYoshi370** [comment] 2020-02-21 15:17
Seems like it, but could you reproduce the issue?

**Comment by gingerbeardman** [comment] 2020-02-21 16:25
I'm yet to try. Will do so ASAP.
