### ISSUE TITLE
Unable to boot DSi Menu from quick menu 

### ISSUE THREAD

**Issue by Alexyo21** [DS-Homebrew/TWiLightMenu#1736] opened 2021-12-28 20:20 UTC
**Console Configuration:** I’m running a Nintendo DSi XL with a 32gb size reduced sd card, with UNLAUNCH 2.0 and HiyaCFW latest  installed with autoboot in twilightmenu++ installed, all running on 1.4.5Eu firmware ( the setup is made using the the 1-2 days ago, release).

**TWiLight Menu++ 23.3.1 (hotfix):** release date one day ago, 27/12/2021. I’m using the stable version not nightly.
**TWiLight Menu++ Theme:**  I’m running the 3ds theme of Homebrew channel with hbl music also in DSi mode.

### Expected behaviour
 when you press open DSI menu from the quick menu in twilightmenu, showing pressing start, it should boot the DSi menu, easily. Before

### Actual behaviour
 instead when you press boot  DSI MENU from twilightmenu, reboot all HiyaCFW, it’ll show also the boot logo and doesn’t go into DSi menu, it’ll send you back to twilightmenu. I want to say using the old version about the October version, the problem doesn’t happen.

### Steps to reproduce

1.install HiyaCFW(setting up splash screen and autoboot title at the first installation of HiyaCFW) and UNLAUNCH and make a setup in the twilight settings. 
2.After that in twilightmenu, press start to show the the quick menu, press open/boot  DSi Menu, 
3.Then it’ll auto-reboot into twilightmenu and you are at the beginning again.

**Comment by spellboundtriangle** [comment] 2022-04-25 14:18
I can't reproduce this, I think? Trying to, it sends me to the SYSNAND DSi Menu (not sure if it's *supposed* to send me to the SDNAND).

**Comment by Epicpkmn11** [comment] 2022-04-25 18:48
I think you need to disable Autoboot Title and set `NO BUTTON` to `BOOT.NDS` (TWiLight Menu++) in Unlaunch options. Using Autoboot Title is no longer recommended as it has no benefit and just slows down boot times.

**Comment by Alexyo21** [comment] 2022-04-30 02:07
Hi, sorry I noticed now your answers. Ok I'll send the nand, do you want the virgin nand without unlaunch or the one with it installed?

**Comment by Alexyo21** [comment] 2022-04-30 02:08
> I think you need to disable Autoboot Title and set `NO BUTTON` to `BOOT.NDS` (TWiLight Menu++) in Unlaunch options. Using Autoboot Title is no longer recommended as it has no benefit and just slows down boot times.


I think you're right but with version of past year October version, it worked great.

**Comment by NightScript370** [comment] 2022-06-29 15:30
This may be moot, considering now Unlaunch handles TWiLight Menu++ instead of hiyaCFW.
Closing unless OP tells me that it's still a problem.

**Closed by NightScript370** 2022-06-29 15:30 UTC
Labels: bug

**Comment by Alexyo21** [comment] 2022-06-29 20:28
Fixed it's not a problem anymore. Good job!!!👏🏻👏🏻

**Comment by NightScript370** [comment] 2022-06-29 20:29
Thanks for reporting it. Let me know if this (or any other issue) occurs (again). We'd be glad to assist you! :D
