### ISSUE TITLE
RetroAchievements support

### ISSUE THREAD

**Issue by Coloradohusky** [DS-Homebrew/TWiLightMenu#2116] opened 2022-12-06 03:58 UTC
**Is your feature request related to a problem? Please describe.**
Seeing as RetroAchievements supports DS games, I'd love to be able to obtain achievements while playing DS games on my 3DS. They have an integration repo [here](https://github.com/RetroAchievements/RAIntegration), and an interface [here](https://github.com/RetroAchievements/RAInterface), which could be able to be used for RAchievement integration into TWiLightMenu++.

**Describe the solution you'd like**
DS games having achievement support through TWiLightMenu

**Comment by lifehackerhansol** [comment] 2022-12-06 03:59
Duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/1461

**Closed by lifehackerhansol** 2022-12-06 03:59 UTC
Labels: enhancement
