### ISSUE TITLE
Request to Add NDS - Wii Connectivity

### ISSUE THREAD

**Issue by Ace-Stallion** [DS-Homebrew/TWiLightMenu#2386] opened 2024-04-03 23:37 UTC
Cannot currently connect to the Nintendo Wii for games such as Pokémon Battle Revolution while using the application.

**Comment by RocketRobz** [comment] 2024-04-03 23:38
Duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/415

**Closed by RocketRobz** 2024-04-03 23:38 UTC
Labels: enhancement
