### ISSUE TITLE
Twilight menu theme editor 

### ISSUE THREAD

**Issue by andyrock922** [DS-Homebrew/TWiLightMenu#2331] opened 2023-12-10 15:59 UTC
**Is your feature request related to a problem? Please describe.**
The 3ds has 4 type of 3ds theme editors Kame-editor, YATA+, YATA+ online, and Usagi3DS.
**Describe the solution you'd like**->
 With the twilight menu theme editor you can make themes in the editor. To make a twilight menu theme now you have to change files of textures pictures and do theme configuration 
**Describe alternatives you've considered**
Make twilight menu themes with editing files within SD card
**Additional context**
![IMG_0509](https://github.com/DS-Homebrew/TWiLightMenu/assets/108361918/3ac7d76e-08a3-4e3d-aed3-f7256662d2f7)

**Comment by spellboundtriangle** [comment] 2023-12-11 01:58
Duplicate of #783

**Closed** 2023-12-11 04:25 UTC
Labels: enhancement
