### ISSUE TITLE
Soft reset not responding properly (NDS ROMs)

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/TWiLightMenu#1250] opened 2020-12-01 21:16 UTC
**Console Configuration:**  Nintendo DSi XL with Unlaunch 2.0
**TWiLight Menu++ Version:** 17.1.1
**TWiLight Menu++ Theme:**  3DS Light

### Expected behaviour

 After doing the soft reset (L + R + DOWN + B) you should be able to return to the TWiLight Menu (applicable to NDS ROMs)

### Actual behaviour

 After doing the soft reset the screen goes blank and does not return to the TM. If the power button is pressed to reset the console, it does not respond either and the screen remains blank. You need to turn the console off and back on to re-enter the TM.

**Comment by RocketRobz** [comment] 2020-12-01 21:19
Make sure you have `boot.nds` on the SD root.

**Comment by SofyUchiha** [comment] 2020-12-01 21:21
It is at the SD root :(

![image](https://user-images.githubusercontent.com/70182567/100798194-0b5aa180-3402-11eb-9f55-870f7f026866.png)

**Comment by RocketRobz** [comment] 2020-12-01 21:24
idk what's going on then.
Closing, since I can't reproduce.

**Closed by RocketRobz** 2020-12-01 21:24 UTC
Labels: bug, cannot reproduce
