### ISSUE TITLE
DSTT based clones do not autoboot on non-SDHC

### ISSUE THREAD

**Issue by lucasmr** [DS-Homebrew/TWiLightMenu#1283] opened 2020-12-31 13:29 UTC
**Console Configuration:** NDS Lite, r4isdhc.com card 
**TWiLight Menu++ Version:** v18.0.0 
**TWiLight Menu++ Theme:** 

### Expected behaviour
Menu should boot up.

### Actual behaviour

A message `FAT init failed!` is displayed if using a 2GB SD card. This card is working properly if using the default kernel (2019 r4isdhc gold pro). Using a 8GB SD card loads fine.

### Steps to reproduce

1. Format a 2GB SD card with FAT32
2. Copy files
3. Boot (use autoboot)

**Comment by Squall-Leonhart** [comment] 2021-01-31 04:48
the default cluster size for 2GB cards is 4KB, less than 16KB can cause file system read issues with the fat library used, and 32KB is most optimal for SD reads of files tens or hundreds megabytes in size.

**Comment by hansoljin** [comment] 2021-04-23 07:17
Actually, a 2GB SD card cannot even format to 32KB clusters using FAT32. That's why FAT16 is used as default when formatting a 2GB SD card. I can even confirm that formatting to FAT16, 32KB clusters work just fine.

This may need to be elaborated on in the DSi guide and the wiki. If 32KB clusters is a must (and it is), then a note for people using SD cards 2GB or less to use FAT16 (also known as FAT on Windows) would be necessary.

**Comment by Squall-Leonhart** [comment] 2021-04-23 07:24
> Actually, a 2GB SD card cannot even format to 32KB clusters using FAT32

Actually, yes it can but you're getting into CMD vs GUI differences to achieve it.

**Comment by hansoljin** [comment] 2021-04-23 08:02
You appear to be correct, `mkdosfs` did format it to FAT32 with 32KB clusters; however, it did give me a warning that cluster was larger than recommended. Let's see if that warning is valid...

I have 5 TWiLight compatible flashcards. I'll list my observations of FAT32, 32KB clusters on a 2GB SD card with each flashcard, and list it below:

- **Acekard 2.1**
    - Original kernel: freezes on "Loading"
    - TWiLight autoboot: white screen

- **Original R4**
    - Original kernel: Couldn't find _DS_MENU.DAT
    - TWiLight autoboot: Couldn't find _DS_MENU.DAT
 
- **M3 Simply**
    - Original kernel: Couldn't find _DS_MENU.DAT
    - TWiLight autoboot: Couldn't find _DS_MENU.DAT

- **DSTT**
    - Original kernel: white screen
    - TWiLight autoboot: white screen

- **R4i-Gold.com V1.4.1**
    - Original kernel: white screen
    - YSMenu: white screen
    - TWiLight autoboot: white screen

Just to make sure this wasn't a problem with just these carts, I tested 4 other flashcards (not TWiLight supported, so I won't list those):

- **r4isdhc.com.cn**
    - Original kernel: Can't open _dsmenu.dat

- **Ace3DS+**
    - Original kernel: Couldn't find _DS_MENU.DAT

- **N5**
    - Original kernel: black screen

- **M3 DS Real**
    - Original kernel: black screen
    - YSMenu: white/black screen


For the fun of it, I threw TWiLight-DSi into this SD and attempted to boot my DSi, which has Unlaunch installed:

- **Unlaunch autoboot**
    - Black screen when autobooting.
- **Unlaunch menu**
    - When loading Unlaunch menu, every single file name is shown corrupted on the SD card.


If there's anything I learned from this experience, it's one thing: There's a reason Windows doesn't let you format a 2GB SD card to FAT32 using 32KB clusters.

Moral of the story: _just format it to FAT16, 32KB clusters._ It works.

**Comment by hansoljin** [comment] 2021-04-23 09:24
Anyway, I did some testing.

It appears the issue is around the specific DLDI patch that TWiLight Menu uses for this card. Right now, it is using boyakkey's DSTT DLDI. 

This specific DLDI appears to be the true reason why the timebomb cart, such as the OP's, is not working. In fact, I even reproduced this issue on a genuine DSTT. 

How I figured out the DLDI was the issue: I tried loading the original kernel first, then booted into TWiLight Menu++. This worked. The kernel automatically DLDI patches anything that is homebrew, so that means it was auto-DLDI-patched correctly. What I concur from that is that the DLDI library used to patch TWiLight at build time isn't working.
I then used dlditool to patch it using the original TTCARD IO DLDI. When using this, TWiLight Menu++ successfully autobooted on both the DSTT and my R4i-Gold V1.4.1 (a timebomb cart that functions identically to OP's r4isdhc.com card.)

So from my testing, it seems TTCARD IO Library will work, while boyakkey's library doesn't. Preferably further testing should be done, however, because the TTCARD IO Library is quite dated.

**Comment by hansoljin** [comment] 2021-04-23 11:56
[R4i-SDHC Autoboot.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/6365043/R4i-SDHC.Autoboot.zip)

For those who use the DSTT or R4i-SDHC, r4isdhc.com cards, etc, autoboot files, if you want to test it out, these are patched with the TTCARD IO Library. I have personally tested this working on 2GB SD cards. Preferably test other SD card sizes, if possible. As long as it boots, it is good.

**Comment by lifehackerhansol** [comment] 2021-05-14 22:40
This issue has been fixed with the PR above and should be closed.

**Comment by lifehackerhansol** [comment] 2021-05-17 20:14
So that PR didn't go well.

Unfortunately, there won't be a way to get around this without a rewrite of the DLDI to allow FAT16 initializing. Which should be possible, but unlikely.

**Comment by lifehackerhansol** [comment] 2022-02-14 17:48
The onends branch _can_ solve this issue, but that seems like a goal too far away for now.

**Closed** 2024-11-01 15:28 UTC
Labels: enhancement, Flashcard, triaged
