### ISSUE TITLE
O3DS: reboot from NDS-Bootstrap to TWiLightMenu returns to HOME Menu. (If this is an NDS Bootstrap issue, I'll move it)

### ISSUE THREAD

**Issue by YYoshi241** [DS-Homebrew/TWiLightMenu#544] opened 2019-04-15 20:33 UTC
### Your console

Tell us which console do you have:

OLD 3DS (OG)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [X]  Luma3DS (9.1, 9.1-4c9fe18, 8.1.1)
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[8.0.0 (also happens on 7.1.0-7.4.1)]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Return to TWiLightMenu

### Actual behaviour

Returns to 3DS HOME Menu

### Steps to reproduce

1.RUN any ROM from TWiLightMenu
2.Press/hold L+R+St+SL
3.Wait
4.Returns to 3DS HOME Menu

Additional Info:
This started after the 7.1.0 release (I didn't post it since my OG 3DS shoulder buttons stopped working around that time.)
Then after the v8.0.0 release with NDS-Bootstrap 0.18, I thought that would have fixed it, but it didn't (Yeah I got the Shoulder buttons working again). Then I reinstalled TWiLightMenu and even tried using the old CIA from v7.0.0 and the Launcher v2.1.1 (Which does boot v8.0.0, but still has the same issue)
The weirdest thing with this is my OTHER 3DS, a OLD 3DS XL, DOESN'T do this.
The system type is 2 (o3ds) in the config btw.
The system acts like you pressed the HOME button in DS(i) mode. (if I hold HOME after doing this FastBoot3DS would load, just like if I held HOME after closing a DS game)

Is this a one console issue or can this be fixed?
Should I supply more info?
Is this a TWiLightMenu Issue or NDS-Bootstrap? 
(if this is a NDS-Bootstrap related issue, I can move or cross-post this on the NDS-Bootstrap Issues page.)

Note: this doesn't have to be High priority, as it is a backup system, but should still be looked at.
Note2: Sorry for not posting it when 7.1.0 came out. I haven't done much with this system and forgot about it. (plus my internet sucks)

**Comment by MasterGamingYT** [comment] 2019-04-15 22:17
Does it happen on the nightly builds?

**Comment by FlameKat53** [comment] 2019-04-15 22:18
That won’t help, the latest nightlies don’t do much for actual things in TWiLight menu, and they are very close to the current 8.0.0 version anyway

**Comment by ErdbeerbaerLP** [comment] 2019-04-21 18:25
My o3ds has the same issue (i already posted it earlier, see https://github.com/DS-Homebrew/TWiLightMenu/issues/248). Both key kombos result in re-launch to home menu

**Comment by TateStangelo** [comment] 2019-05-16 12:46
I have the same issue. I re-downloaded the files and when I started a game up, it just went to the home menu.

**Comment by FlameKat53** [comment] 2019-10-03 14:44
It's been a while, delete the twilight menu++ cia files by using FBI (if it has the delete title and ticket option use that), delete the `sdmc:/_nds/` folder and reinstall twilight menu++ like new and see if that fixes the issue

**NOTE: you don't have to delete the _nds folder, you can just rename it and keep all your settings**

**Comment by NightYoshi370** [comment] 2020-01-30 04:48
I can't reproduce this on my Old3DS with Luma 10.X
Closing

**Closed by NightYoshi370** 2020-01-30 04:48 UTC

**Comment by YYoshi241** [comment] 2020-03-07 21:08
Update 3/7/2020: as of nds-bootstrap v0.30.1 and TWLM++ 12.2.1, reboot is once again working. Also I know that this issue page is dead.
