### ISSUE TITLE
red squares screen while booting a cartridge

### ISSUE THREAD

**Issue by leapbtw** [DS-Homebrew/TWiLightMenu#1099] opened 2020-06-25 12:18 UTC
the bug: while booting a cartridge from twilight menu in DS mode, the top screen becomes white, the bottom one is black with 4 red squares. the rightmost one becomes yellow, then green, then red: then the second rightmost becomes yellow and everything freezes like this

how to reproduce: it happens me when i try to boot my pokemon platinum cartirdge, and in the GBA slot of twilight menu i have my pokemon emerald rom, i would like to use pal park but instead of booting pokemon platinum while i open it this happens
![Schermata 2020-06-25 alle 14 15](https://user-images.githubusercontent.com/36914991/85718304-ac745c00-b6ee-11ea-8081-cf58b20f6e4a.png)

**Comment by NightYoshi370** [comment] 2020-06-25 12:58
Dupe of #1040, already known and fixed in latest nightly

**Closed by NightYoshi370** 2020-06-25 12:58 UTC
Labels: bug
