### ISSUE TITLE
[GRAPHICAL] Long Game Titles sometimes bleed through in Quick Menu

### ISSUE THREAD

**Issue by The-NinToaster** [DS-Homebrew/TWiLightMenu#553] opened 2019-04-17 12:09 UTC
### Your console

Tell us which console do you have:
- [x]  Old 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:
3DS/2DS:
- [x]  Luma3DS

### TWiLight Menu++ version

Tell us which versions you are using:
- [x]  Release _[8.0.0]_

### Expected behaviour
Titles are contained in their textbox in the Quick Menu, 
Fonts normally decrease in size to accommodate for long titles.

### Actual behaviour
Title bleeds out of the textbox. Attached is an example. 
![image](https://user-images.githubusercontent.com/31828869/56286588-7bfb6000-60f0-11e9-9f2c-381a831fce5d.png)

### Steps to reproduce

1. Load a game that has a title longer than 15 characters in one or more lines, so you can get it in the Quick Menu for next time. My example is Square Enix's
Dragon Quest Heroes: Rocket Slime.
2. Restart TWiLightMenu++ and go to the Quick Menu.

**Comment by arraystock** [comment] 2019-04-18 14:58
Possible duplicate of #310.

**Comment by NightYoshi370** [comment] 2019-04-22 05:24
This is a duplicate of #310. Use that issue to discuss this further

**Closed by NightYoshi370** 2019-04-22 05:24 UTC
Labels: bug
