### ISSUE TITLE
R4 Gold+ RTS autoboot won't work and won't boot NDS games without nds-bootstrap

### ISSUE THREAD

**Issue by olokos** [DS-Homebrew/TWiLightMenu#1025] opened 2020-05-07 06:57 UTC
**Your console configuration:** DS Lite with this flashcart
![Flashcart picture](https://www.nds-card.com/UploadFile/P575_1.JPG)
**TWiLight Menu++ Version:** 15
**TWiLight Menu++ Theme:** R4
### Expected behaviour
Moving autoboot should make twilightmenu to autoboot
Setting nds-bootloader to no should load nds games using wood kernel 1.64

### Actual behaviour
DS Lite only autoboots to Woodkernel, but not to twilightmenu
Instead of booting the nds games with wood kernel firmware it says Error:1 and game doesn't start
### Steps to reproduce

1. Download Twiglightmenu.7z release 15
2. Install twilight menu as per guide, then copy `TWiLightMenu.7z\Flashcard users\Autoboot\akMenu-Wood UI root\__rpg\` to `root of microsd/_rpg`
3. DS Lite should autoboot to Twitlight Menu, but it doesn't.
4. Boot Twilightmenu manually by executing BOOT.NDS within wood kernel AKMenu
5. Press select for settings
6. Set nds-bootloader to no (so woodkernel firmware is used for loading games)
7. Error: 1 appears and game doesn't get loaded

I will provide whatever is neccesary to fix this.

The flashcart in the picture is the latest R4 flashcart released and everybody is recommending to buy it in 2019/2020 for DS Lite and the DS family in general, so I think it's pretty important.

**Comment by adamj-codethink** [comment] 2020-05-07 12:45
Also seeing issues with this card, i can't get anything to boot =/

**Comment by adamj-codethink** [comment] 2020-05-07 20:37
I just seen a blank black screen when booting with this card

**Comment by olokos** [comment] 2020-05-28 16:51
@RocketRobz 
Sorry for bothering you, but this cart is currently the one recommended by everybody in EU and readily available.

**Comment by NightYoshi370** [comment] 2020-06-12 01:04
Half of the issue is fixed in the latest commits
The other half of the issue cannot be fixed without some serious overheads on how TWiLight Menu++ launches kernels for playing

**Comment by olokos** [comment] 2020-06-17 18:20
I'm really happy to see some progress on this.

Unfortunately I followed the instructions and found following issues:

Step4 for flashcard instructions:
``Copy boot_fc.nds in Flashcard users to microSD root.``
There's no boot_fc in Flashcard users

Autoboot still doesn't autoboot.

After nds-bootstrap is disabled instead of booting into the game, seems like _wfwd is launched, but instead of the game, a broken akmenu with no background image and no text anywhere.

I used the v15.2.0 release with current instructions, using Original R4 folder with the flashcart in the 1st post.

**Comment by unresolvedsymbol** [comment] 2020-07-31 20:13
@olokos I know this is quite a bit late but have you tried the new R4i Gold 3DS Plus autobooters in the latest release?

**Comment by olokos** [comment] 2020-08-02 04:13
@unresolvedsymbol  sure thing, it's just I'm a litte bit exhausted right now, I'll bookmark this issue.
In case I do not reply over 48 hours - please do remind me, if you could please, by mentioning me again in this issue, just in case. ;)

**Comment by unresolvedsymbol** [comment] 2020-08-04 02:52
@olokos lol, well our cards are identical so just use the `Flashcard Loader` in the latest rel. In fact if you modify the ini's you can a little tediously use cheats by holding B on startup and setting cheats for the game they'll carry over to TWiLightMenu (if you disable B4DS of course)

**Comment by ShadowEO** [comment] 2020-08-04 07:49
I am unable to autoboot my R4i Gold RTS (looks very similar to the above, but the RTS text is green like the one referenced in #1143)

I am able to autoboot by making WoodR4 autoload the last ROM and booting BOOT.NDS with it, but the included _DS_MENU.DAT for autobooting results in only a black screen.

(Btw, other R4i Gold RTS users, if you disable B4DS and copy the "reset" and "rts" settings from your _rpg/globalsettings.ini over to the _wfwd/globalsettings.ini, you can have the R4i RTS work in game as long as you're not loading a ROM from the console's SD card which forces the use of nds-bootstrap)

**Comment by olokos** [comment] 2020-08-30 14:49
I tried installing the 16.1.0 version, but the folders are pretty confusing, but from what I have gathered, I need to download 
TwilightMenu-Flashcard.zip
then
extract the stock `woodkernel 1.64` to sdcard
extract `TwilightMenu-Flashcard.zip`'s folder `_nds/*` to sdcard
extract `TWMenu 16.1.0\Flashcart Loader\R4iDSN & R4i Gold RTS` to sdcard
extract `TWMenu 16.1.0\Autoboot\R4iDSN & R4 Ultra\_DS_MENU.DAT` to sdcard

this ends up in white screen on boot and complete freeze, so I guess Autoboot is out of the question

Restoring _DS_MENU.DAT from `Flashcart Loader\R4iDSN & R4i Gold RTS` allows to boot TwilightMenu using R4 woodkernel, but once the initial animation is over and the first animation of folders dropping from top for user to interact with it - suddenly it freezes completely with sound freezing aswell.

2nd attempt to use TWMenu was:
Remove everything
extract the stock `woodkernel 1.64` to sdcard
extract `TwilightMenu-Flashcard.zip`'s folder `_nds/*` to sdcard
extract `TWMenu 16.1.0\Flashcart Loader\R4iDSN & R4i Gold RTS` to sdcard
DO NOT copy _rpg folder from `TWMenu 16.1.0\Flashcart Loader\R4iDSN & R4i Gold RTS`, but copy the rest of files in there

No autoboot, as expected BUT twilight menu does run roms with nds-bootstrap and no freezing in sight!

Not only that, but nds-bootstrap - no also works following my 2nd procedure, albeit it doesn't detect saves previously made.

**Comment by unresolvedsymbol** [comment] 2020-09-22 02:39
@olokos Stock wood is unnecessary because the flashcart loader folder already contains it, also the `_rpg` folder is quite important because it contains the configuration to autoboot TWLM. Pretty sure you got a white screen on the first attempt because you wrote that you're only extracting TWLM's `_nds` folder (you need BOOT.NDS too)

Anyway the flashcart loader is primarily for using wood for booting games without nds-bootstrap, but glad you got it working.

**Comment by lifehackerhansol** [comment] 2021-09-28 03:21
A whole year late, but we're almost close to figuring this out. (Sorry it took too long).

Feel free to take a look at the build artifact and test.

**Closed** 2021-09-28 20:48 UTC
Labels: bug

**Comment by user2222222222** [comment] 2022-02-01 16:29
R4 SDHC GOLD Pro can't boot.  Tried both R4.dat options in autoboot folder.
I'm posting because of this great work-around:
https://www.reddit.com/r/flashcarts/comments/mtjww5/reset_to_twilight_menu_with_ysmenu/gv06ld9/

I haven't tried it.  The only problem is that if you don't use the button hold shortcut to reset, it's just going to reboot back into the game instead of the menu.

A better option might be to try hex editing YSMenu's R4.dat to boot into a different menu folder: rather than TTMenu, try changing to TTBoot then configure the ini file in TTBoot to auto start TwilightMenu. 

Or, a simpler solution, if you don't want to use YS as the rom loader: just make ys auto load twilight.

I'm confident this would work for anyone interested in getting Twilight going with YS.  As for me, I'm sticking with the YS menu: nds-bootstrap fails on too many roms.

**Comment by lifehackerhansol** [comment] 2022-02-01 16:53
This issue is for a different flashcart. Please file a new one.

**Comment by olokos** [comment] 2022-06-19 02:41
The bug is 100% fixed and everything works perfectly now!

Great work, thank You guys, also I'm not sure if it's placebo, but Twilight menu seems to scroll much faster and snappier than before, which is amazing! :)
