### ISSUE TITLE
3ds theme graphic bug

### ISSUE THREAD

**Issue by vvvlad99** [DS-Homebrew/TWiLightMenu#1878] opened 2022-03-30 19:15 UTC
Console: DSI
TWiLight Menu++ Version:** 24.3.1
TWiLight Menu++ Theme:** 3DS BOTH SKINS

this problem is only present when using the 3ds theme, which I like much more than the standard dsi, while scrolling the cover there is always a fragment of the old one for a second, before the new one appears, also if the next game does not have a cover, this piece remains on the screen all the time.DSI theme work fine with same boxarts
![308A62BC-3F94-4E2E-802C-0ABE81C43A9D](https://user-images.githubusercontent.com/4732551/160913052-91cbcc66-8085-4ac4-85d5-7d969b804412.jpeg)

**Comment by vvvlad99** [comment] 2022-03-30 19:26
https://user-images.githubusercontent.com/4732551/160914943-41770182-cb9a-43d3-82e9-0659059cff2c.MOV

**Comment by lifehackerhansol** [comment] 2022-03-30 19:31
Duplicate of https://github.com/DS-Homebrew/TWiLightMenu/issues/1785.

**Closed by lifehackerhansol** 2022-03-30 19:31 UTC
Labels: bug
