### ISSUE TITLE
Bug tema 3ds

### ISSUE THREAD

**Issue by ParaLamaa** [DS-Homebrew/TWiLightMenu#2421] opened 2024-05-30 00:03 UTC
Bug dos cubos tema 3ds não resolvido

**Comment by RocketRobz** [comment] 2024-05-30 00:15
Please post only in English.
Also, make sure you're using v27.3.3.

**Comment by RocketRobz** [comment] 2024-05-30 00:25
Duplicate of #2387

**Closed by RocketRobz** 2024-05-30 00:25 UTC
Labels: bug
