### ISSUE TITLE
hiyaCFW autoboot broken starting with v24.5.0

### ISSUE THREAD

**Issue by robmccoy93** [DS-Homebrew/TWiLightMenu#1931] opened 2022-05-07 20:32 UTC
Seems 24.7.0 just causes a persisting white screen when booting using hiyacfw autoboot no button setting. I had to roll back to  v24.3.1 to get things to boot again.

**Comment by RocketRobz** [comment] 2022-05-07 20:33
Try setting Unlaunch to directly boot TWLMenu++ instead of hiyaCFW.

**Comment by robmccoy93** [comment] 2022-05-07 20:45
Hm that seems to work. wonder why hiyaCFW doesn't want to boot it? I don't know why but I was told that using hiya gave it more patches or something so it was supposed to be better to do that method at the time. I haven't updated in a year almost.

**Comment by RocketRobz** [comment] 2022-05-08 19:42
It seems the issue is caused by re-implementing the animated icon.

**Comment by RocketRobz** [comment] 2022-05-27 02:33
The new current version should fix this, and I recently haven't heard anyone with this issue, so it's safe to assume this is indeed fixed.

**Comment by RocketRobz** [comment] 2022-05-29 08:19
It has been reported by someone else that the issue still occurs.
It seems the issue is not related to the icon.

**Comment by GIKAS123** [comment] 2022-05-29 12:23
If it helps at all I found out that if I press the power button on the dsi really quickly while on the white screen it boots just fine.

**Comment by luizluan** [comment] 2022-06-07 13:58
It's safe to use TWLMenu++ without HiyaCfw?

**Comment by RocketRobz** [comment] 2022-06-07 19:00
The issue should be fixed in v24.9.0.

**Comment by luizluan** [comment] 2022-06-07 23:14
The error still occurs in version 24.9.0. I had to change the boot to go straight to the TwilightMenu.

**Comment by luizluan** [comment] 2022-06-07 23:15
I moved the nds file, the title folder and Boot.nds.

**Comment by RocketRobz** [comment] 2022-06-07 23:31
Commit 6de18542 has officially fixed it.

**Closed by RocketRobz** 2022-06-07 23:31 UTC
Labels: bug
