### ISSUE TITLE
Roms in folder not showing when using WoodUI

### ISSUE THREAD

**Issue by Adro8** [DS-Homebrew/TWiLightMenu#1037] opened 2020-05-16 07:55 UTC
-DSi with Unlaunch 2.00  
-TWiLight Menu++ Version v15.0.1
-WoodUI

When i play a game and softreset to go back to the nds game folder the files dissapear and i have to exit and enter the folder for them to show.

![20200516_002848](https://user-images.githubusercontent.com/65439833/82114113-9185f380-970f-11ea-9414-905922dbb65a.jpg)
![20200516_002831](https://user-images.githubusercontent.com/65439833/82114118-98ad0180-970f-11ea-9e60-ea73503778d2.jpg)

I think this happens in the latest two versions, since AKmenu was renamed to woodUI

Steps to reproduce
1. Change your theme to WoodUI and go to your games folder
2. Launch a game or restart the console

**Comment by Aeuko** [comment] 2020-05-28 01:32
-TWiLight Menu++ Version v15.1.1
-WoodUI

I also encountered this situation, and when you use WordUI for the first time, all GB games will fail.

**Comment by jeffcox** [comment] 2020-06-05 19:23
Any information I can provide to help get this one fixed?  Annoying to have to go up and back into the directory every time.

Also running on a DSi with Unlaunch.

**Comment by mjosephdelrosario** [comment] 2020-06-07 00:51
Replicated on my part also.

**Comment by cyruzwings** [comment] 2020-06-08 08:15
have same problem, I try reinstall and using unlaunch 1.8 to 2.0 and the result still same.
using another theme no problem found, guess the problem is the Wood UI Theme.
I'm now using unlaunch 1.9
TWLight Menu++ v15.1.1

**Comment by chyyran** [comment] 2020-07-05 22:26
Fixed in #1109

**Closed** 2024-05-04 06:00 UTC
Labels: bug, akmenu Theme, triaged
