### ISSUE TITLE
Dual-Slot Mode Support 

### ISSUE THREAD

**Issue by iWockstar** [DS-Homebrew/TWiLightMenu#2327] opened 2023-11-18 06:41 UTC
**Is your feature request related to a problem? Please describe.**
Some NDS games allow you to unlock specific items or do certain missions if you have that NDS games inserted in your NDS and specified GBA cartridge in your NDS. This feature does not work on Twilight Menu / 3DS due to not having a GBA cartridge slot.

**Describe the solution you'd like**
Would you guys be able to add dual-slot mode into twilight menu++? It'll make a lot of people happy and it'll also be a cool future we can tell people as a community.

**Describe alternatives you've considered**
If you can't directly implement dual-slot mode into twilight menu++, making it possible with an R4 card would also be very helpful

**Additional context**
I'm not qualified in coding or anything like that and I'm new to Twilight Menu++, so if this is not possible directly on the 3DS's Twilight Menu++ or an R4 card let me know. Also let me know if it's possibly already in the works. Thanks!

**Comment by SleepyLark** [comment] 2023-11-18 20:39
I think this is something nds-bootstrap would have to handle since it would have to do some patches in the game to redirect where to look for the GBA saves. Shouldn't be impossible to implement but it's not a high priority at the moment. In fact there's already an issue for it here:
https://github.com/DS-Homebrew/nds-bootstrap/issues/19

**Comment by RocketRobz** [comment] 2023-11-19 01:19
Duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/19

**Closed by RocketRobz** 2023-11-19 01:19 UTC
Labels: enhancement
