### ISSUE TITLE
Dsi do not sleep when close lid in Rom selecting menu.

### ISSUE THREAD

**Issue by tomudo** [DS-Homebrew/TWiLightMenu#1808] opened 2022-02-20 13:02 UTC
**Console Configuration:**  DSi (normal model) Japan
**TWiLight Menu++ Version:**  Valentine's Day Release (2022)
**TWiLight Menu++ Theme:**  Saturn, DSi, 3DS, Homebrew

### Expected behaviour

DSi Sleep when lid closed in ROM selecting menu 
### Actual behaviour

It does not sleep in ROM selecting menu, everywhere else, in Game, config menu could be slept without problem. R4 Theme could be slept.

### Steps to reproduce

1. Select Saturn, DSi, 3DS, Homebrew Theme
2. Go to ROM selecting menu
3. Close DSi lid

**Comment by spellboundtriangle** [comment] 2022-02-20 13:07
Sleep mode is currently bugged in the DSi-based themes, so it was intentionally disabled.

**Comment by lifehackerhansol** [comment] 2022-02-20 16:58
Duplicate of #1409.

**Closed by lifehackerhansol** 2022-02-20 16:58 UTC
Labels: bug
