### ISSUE TITLE
Screenshot function?

### ISSUE THREAD

**Issue by yonerue** [DS-Homebrew/TWiLightMenu#1444] opened 2021-05-01 05:04 UTC
I was thinking, now with the new in-game menu, introduced in the previous version of bootstrap v0.37.0. Wouldn't it be great to have the option to take screenshots similar to Rosalina's menu? I don't think it is something that complicated to implement in my own eyes (I have no experience in coding by the way). But it would be a great addition and I hope it can be added in a future!

**Comment by RocketRobz** [comment] 2021-05-01 05:08
Duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/187

**Closed by RocketRobz** 2021-05-01 05:08 UTC
Labels: enhancement
