### ISSUE TITLE
V 24.6 won't allow DSI LL go on sleep mode.

### ISSUE THREAD

**Issue by Akirah10** [DS-Homebrew/TWiLightMenu#1929] opened 2022-05-06 23:07 UTC
twilight menu v24.6 don't allow DSI LL to go on sleep mode.

**Console Configuration:**  DSI LL, TWM 24.6, hiya cfw, unlaunch.
**TWiLight Menu++ Version:** 24.6 earthday
**TWiLight Menu++ Theme:** No theme

### Expected behaviour
Expecting console go in sleep mode when lid is closed

### Steps to reproduce

1
3.

**Comment by RocketRobz** [comment] 2022-05-06 23:09
@lifehackerhansol meant for future reference.
The issue occurs for the reason stated earlier in [this](https://github.com/DS-Homebrew/TWiLightMenu/issues/1928#issuecomment-1120066370) post.

Duplicate of #1929

**Closed by RocketRobz** 2022-05-06 23:09 UTC
Labels: bug

**Comment by Akirah10** [comment] 2022-05-06 23:13
Thank u. Appreciate your response
