### ISSUE TITLE
Freezing Issuse 

### ISSUE THREAD

**Issue by juliathemew64** [DS-Homebrew/TWiLightMenu#1617] opened 2021-09-18 23:10 UTC
Happens with any nds game I try to run works fine for a few minutes than crashes.

**Comment by lifehackerhansol** [comment] 2021-09-18 23:13
Please fill the issue templates.

**Comment by juliathemew64** [comment] 2021-09-18 23:15
Where? I see no template

**Comment by RocketRobz** [comment] 2021-09-18 23:17
The one you replaced with this:


> Happens with any nds game I try to run works fine for a few minutes than crashes.

**Comment by juliathemew64** [comment] 2021-09-18 23:20
### Expected behaviour
Game runs without crashing


You can actually play the game 
### Actual behaviour
It crashes randomly 


It crashes randomly
### Steps to reproduce

1.install rom 
2.play 
3.wait till it crashes 
👍

**Comment by RocketRobz** [comment] 2021-09-18 23:22
Which version of TWLMenu++ and nds-bootstrap are you using, and which games?

**Comment by Squall-Leonhart** [comment] 2021-09-19 19:27
I can reproduce this, I'm seeing it in NSMB for instance.

At first i thought it was a TWL clockspeed issue since the first note of the main music note was and changing TWL to NTR made the main music start normally but then the game froze while sitting on the menu anyway.

when the freeze happens the clouds on the top screen corrupt and the logo disappears.

I do have Async and DMA enabled though, so i'll be testing those off next after finishing the update to latest nightly TWLMenu and nds bootstrap.

**Comment by Squall-Leonhart** [comment] 2021-09-19 19:38
Doesn't occur in Release, occurs in Nightly

DMA and Async still enabled

**Comment by Squall-Leonhart** [comment] 2021-09-19 20:06
@juliathemew64  what games did you experience this with, other than NSBM.

**Comment by RocketRobz** [comment] 2021-09-19 23:06
The NSMB freezing issue was caused by how the MPU was set up.
It's now fixed in d2ac27fd.

**Comment by Squall-Leonhart** [comment] 2021-09-20 01:31
Lost in Blue and Lufia are booting to white screen on nightly but work on Release.

**Comment by Squall-Leonhart** [comment] 2021-09-20 05:18
Out of my 142 nds dumps, and excluding pokemon dash and golden sun for obvious reasons, all my games work without freezing.

**Comment by RocketRobz** [comment] 2021-09-29 07:29
Closing due to no response from OP.

**Closed by RocketRobz** 2021-09-29 07:29 UTC
Labels: bug, cannot reproduce
